package com.fongmi.android.tv.player.karaoke;

import android.media.AudioFormat;
import android.media.MediaCodec;
import android.media.MediaExtractor;
import android.media.MediaFormat;
import android.text.TextUtils;

import com.fongmi.android.tv.App;
import com.fongmi.android.tv.player.lyrics.LyricsLine;
import com.github.catvod.crawler.SpiderDebug;

import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.Tensor;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

class BasicPitchTfliteGenerator {

    private static final String MODEL_ASSET = "models/basic_pitch_nmp.tflite";
    private static final int SAMPLE_RATE = 22_050;
    private static final int HOP_SAMPLES = 256;
    private static final int WINDOW_SAMPLES = SAMPLE_RATE * 2 - HOP_SAMPLES;
    private static final int MIDI_OFFSET = 21;
    private static final int MIN_MIDI = 40;
    private static final int MAX_MIDI = 84;
    private static final int MAX_CANDIDATES = 4;
    private static final long WINDOW_MARGIN_MS = 70;
    private static final double MIN_FRAME_ACTIVATION = 0.12;
    private static final double MIN_SEGMENT_RATIO = 0.06;
    private static final double MIN_SEGMENT_SCORE = 0.015;
    private static final long DECODE_EXTRA_MS = 1000;

    private BasicPitchTfliteGenerator() {
    }

    static String build(KaraokeTrackRepository.MediaInput input, List<LyricsLine> lines, KaraokePitchTrackGenerator.Progress progress) throws Exception {
        KaraokePitchTrackGenerator.ProgressReporter reporter = new KaraokePitchTrackGenerator.ProgressReporter(progress);
        if (!KaraokePitchTrackGenerator.canGenerate(input, lines)) throw new IllegalStateException("no timed lyrics");
        reporter.update(1, KaraokePitchTrackGenerator.STAGE_PREPARE);
        List<KaraokePitchTrackGenerator.Segment> segments = KaraokePitchTrackGenerator.segments(lines, input.getDuration());
        if (segments.size() < 3) throw new IllegalStateException("not enough lyric timing");
        AudioBuffer audio = decode(input, segments, reporter);
        if (audio.size() < SAMPLE_RATE) throw new IllegalStateException("audio too short");
        reporter.update(45, KaraokePitchTrackGenerator.STAGE_ANALYZE);
        List<List<KaraokePitchTrackGenerator.PitchCandidate>> candidates = analyze(audio, segments, reporter);
        String text = KaraokePitchTrackGenerator.buildTextFromCandidates(input.getKeyword(), input.getArtist(), segments, candidates, reporter, "Generated by Basic Pitch TFLite from local audio");
        reporter.update(100, KaraokePitchTrackGenerator.STAGE_FINISH);
        return text;
    }

    private static List<List<KaraokePitchTrackGenerator.PitchCandidate>> analyze(AudioBuffer audio, List<KaraokePitchTrackGenerator.Segment> segments, KaraokePitchTrackGenerator.ProgressReporter reporter) throws Exception {
        long startMs = System.currentTimeMillis();
        SegmentScore[] scores = new SegmentScore[segments.size()];
        for (int i = 0; i < scores.length; i++) scores[i] = new SegmentScore();
        try (Interpreter interpreter = new Interpreter(loadModel(), options())) {
            OutputPlan outputPlan = OutputPlan.from(interpreter);
            if (outputPlan.note == null) throw new IllegalStateException("Basic Pitch note output not found");
            ByteBuffer inputBuffer = ByteBuffer.allocateDirect(WINDOW_SAMPLES * 4).order(ByteOrder.nativeOrder());
            int step = WINDOW_SAMPLES;
            int totalWindows = Math.max(1, (int) Math.ceil(audio.size() / (double) step));
            for (int window = 0, start = 0; start < audio.size(); window++, start += step) {
                fillInput(inputBuffer, audio, start);
                outputPlan.clear();
                interpreter.runForMultipleInputsOutputs(new Object[]{inputBuffer}, outputPlan.outputs);
                collect(outputPlan, scores, segments, start);
                reporter.update(45 + (int) Math.round((window + 1) * 33.0 / totalWindows), KaraokePitchTrackGenerator.STAGE_ANALYZE);
            }
            if (SpiderDebug.isEnabled()) {
                SpiderDebug.log("karaoke-pitch", "basic-pitch analyze done cost=%sms samples=%d windows=%d outputs=%s",
                        System.currentTimeMillis() - startMs, audio.size(), totalWindows, outputPlan.describe());
            }
        }
        List<List<KaraokePitchTrackGenerator.PitchCandidate>> result = new ArrayList<>(segments.size());
        for (SegmentScore score : scores) result.add(score.candidates());
        return result;
    }

    private static Interpreter.Options options() {
        Interpreter.Options options = new Interpreter.Options();
        int cores = Runtime.getRuntime().availableProcessors();
        options.setNumThreads(Math.max(1, Math.min(3, cores - 1)));
        return options;
    }

    private static ByteBuffer loadModel() throws Exception {
        try (InputStream input = App.get().getAssets().open(MODEL_ASSET); ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[16 * 1024];
            int count;
            while ((count = input.read(buffer)) != -1) output.write(buffer, 0, count);
            byte[] bytes = output.toByteArray();
            ByteBuffer model = ByteBuffer.allocateDirect(bytes.length).order(ByteOrder.nativeOrder());
            model.put(bytes);
            model.rewind();
            return model;
        }
    }

    private static void fillInput(ByteBuffer buffer, AudioBuffer audio, int start) {
        buffer.rewind();
        for (int i = 0; i < WINDOW_SAMPLES; i++) buffer.putFloat(audio.get(start + i));
        buffer.rewind();
    }

    private static void collect(OutputPlan plan, SegmentScore[] scores, List<KaraokePitchTrackGenerator.Segment> segments, int windowStartSample) {
        float[][][] note = plan.note.values;
        float[][][] onset = plan.onset == null ? null : plan.onset.values;
        int frames = Math.min(note[0].length, plan.note.shape.length > 1 ? plan.note.shape[1] : note[0].length);
        int segmentIndex = 0;
        for (int frame = 0; frame < frames; frame++) {
            long timeMs = Math.round((windowStartSample + frame * HOP_SAMPLES) * 1000.0 / SAMPLE_RATE);
            while (segmentIndex < segments.size() && timeMs >= segments.get(segmentIndex).endMs + WINDOW_MARGIN_MS) segmentIndex++;
            FramePitch framePitch = strongest(note[0][frame], onset == null ? null : onset[0][Math.min(frame, onset[0].length - 1)]);
            int cursor = segmentIndex;
            while (cursor < segments.size()) {
                KaraokePitchTrackGenerator.Segment segment = segments.get(cursor);
                if (timeMs < segment.startMs - WINDOW_MARGIN_MS) break;
                if (timeMs < segment.endMs + WINDOW_MARGIN_MS) scores[cursor].addFrame(framePitch);
                cursor++;
            }
        }
    }

    private static FramePitch strongest(float[] note, float[] onset) {
        FramePitch result = new FramePitch();
        for (int midi = MIN_MIDI; midi <= MAX_MIDI; midi++) {
            int bin = midi - MIDI_OFFSET;
            if (bin < 0 || bin >= note.length) continue;
            double activation = note[bin];
            if (onset != null && bin < onset.length) activation += onset[bin] * 0.25;
            result.offer(midi, activation);
        }
        return result;
    }

    private static AudioBuffer decode(KaraokeTrackRepository.MediaInput input, List<KaraokePitchTrackGenerator.Segment> segments, KaraokePitchTrackGenerator.ProgressReporter reporter) throws Exception {
        KaraokeAudioExtractor.Opened source = null;
        MediaCodec decoder = null;
        try {
            reporter.update(5, KaraokePitchTrackGenerator.STAGE_DECODE);
            source = KaraokeAudioExtractor.open(input);
            MediaExtractor extractor = source.extractor;
            int track = source.track;
            extractor.selectTrack(track);
            MediaFormat format = extractor.getTrackFormat(track);
            String mime = format.getString(MediaFormat.KEY_MIME);
            if (TextUtils.isEmpty(mime)) throw new IllegalStateException("unknown audio mime");
            decoder = MediaCodec.createDecoderByType(mime);
            decoder.configure(format, null, null, 0);
            decoder.start();
            return decodeLoop(extractor, decoder, format, decodeDurationMs(input, format, segments), reporter);
        } finally {
            if (source != null) source.close();
            if (decoder != null) {
                try {
                    decoder.stop();
                } catch (Exception ignored) {
                }
                decoder.release();
            }
        }
    }

    private static AudioBuffer decodeLoop(MediaExtractor extractor, MediaCodec decoder, MediaFormat inputFormat, long durationMs, KaraokePitchTrackGenerator.ProgressReporter reporter) {
        MediaCodec.BufferInfo info = new MediaCodec.BufferInfo();
        AudioBuffer audio = new AudioBuffer(Math.max(SAMPLE_RATE, (int) Math.min(Integer.MAX_VALUE, durationMs * SAMPLE_RATE / 1000L + SAMPLE_RATE)));
        AudioCollector collector = new AudioCollector(sampleRate(inputFormat), audio);
        boolean inputDone = false;
        boolean outputDone = false;
        MediaFormat outputFormat = inputFormat;
        long maxDecodeUs = durationMs > 0 ? durationMs * 1000L : Long.MAX_VALUE;
        while (!outputDone) {
            if (!inputDone) {
                int inputIndex = decoder.dequeueInputBuffer(10_000);
                if (inputIndex >= 0) {
                    ByteBuffer input = decoder.getInputBuffer(inputIndex);
                    if (input == null) continue;
                    int size = extractor.readSampleData(input, 0);
                    long sampleTimeUs = extractor.getSampleTime();
                    if (size < 0 || sampleTimeUs > maxDecodeUs) {
                        decoder.queueInputBuffer(inputIndex, 0, 0, Math.max(0, sampleTimeUs), MediaCodec.BUFFER_FLAG_END_OF_STREAM);
                        inputDone = true;
                    } else {
                        decoder.queueInputBuffer(inputIndex, 0, size, sampleTimeUs, extractor.getSampleFlags());
                        reporter.update(5 + (int) Math.round(Math.max(0, Math.min(1, sampleTimeUs / (double) Math.max(1, maxDecodeUs))) * 36), KaraokePitchTrackGenerator.STAGE_DECODE);
                        extractor.advance();
                    }
                }
            }
            int outputIndex = decoder.dequeueOutputBuffer(info, 10_000);
            if (outputIndex == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
                outputFormat = decoder.getOutputFormat();
                collector.setSourceSampleRate(sampleRate(outputFormat));
            } else if (outputIndex >= 0) {
                ByteBuffer output = decoder.getOutputBuffer(outputIndex);
                if (output != null && info.size > 0) collect(collector, output, info, outputFormat);
                outputDone = (info.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0;
                decoder.releaseOutputBuffer(outputIndex, false);
            }
        }
        return audio;
    }

    private static void collect(AudioCollector collector, ByteBuffer buffer, MediaCodec.BufferInfo info, MediaFormat format) {
        int channels = Math.max(1, format.containsKey(MediaFormat.KEY_CHANNEL_COUNT) ? format.getInteger(MediaFormat.KEY_CHANNEL_COUNT) : 1);
        int encoding = format.containsKey(MediaFormat.KEY_PCM_ENCODING) ? format.getInteger(MediaFormat.KEY_PCM_ENCODING) : AudioFormat.ENCODING_PCM_16BIT;
        ByteBuffer data = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN);
        data.position(info.offset);
        data.limit(info.offset + info.size);
        if (encoding == AudioFormat.ENCODING_PCM_FLOAT) collectFloat(collector, data, channels, Math.max(0, info.presentationTimeUs));
        else collectPcm16(collector, data, channels, Math.max(0, info.presentationTimeUs));
    }

    private static void collectPcm16(AudioCollector collector, ByteBuffer data, int channels, long presentationTimeUs) {
        int samples = data.remaining() / (channels * 2);
        long sourceIndex = collector.sourceIndexOf(presentationTimeUs);
        for (int i = 0; i < samples; i++) {
            float mono = 0;
            for (int c = 0; c < channels; c++) mono += data.getShort() / 32768f;
            collector.add(mono / channels, sourceIndex + i);
        }
    }

    private static void collectFloat(AudioCollector collector, ByteBuffer data, int channels, long presentationTimeUs) {
        int samples = data.remaining() / (channels * 4);
        long sourceIndex = collector.sourceIndexOf(presentationTimeUs);
        for (int i = 0; i < samples; i++) {
            float mono = 0;
            for (int c = 0; c < channels; c++) mono += data.getFloat();
            collector.add(mono / channels, sourceIndex + i);
        }
    }

    private static long decodeDurationMs(KaraokeTrackRepository.MediaInput input, MediaFormat format, List<KaraokePitchTrackGenerator.Segment> segments) {
        long end = 0;
        for (KaraokePitchTrackGenerator.Segment segment : segments) end = Math.max(end, segment.endMs);
        long duration = input != null && input.getDuration() > 0 ? input.getDuration() : 0;
        if (duration <= 0 && format != null && format.containsKey(MediaFormat.KEY_DURATION)) duration = Math.max(0, format.getLong(MediaFormat.KEY_DURATION) / 1000L);
        long target = end > 0 ? end + DECODE_EXTRA_MS : duration;
        return duration > 0 ? Math.min(duration, target) : Math.max(target, SAMPLE_RATE);
    }

    private static int sampleRate(MediaFormat format) {
        return format != null && format.containsKey(MediaFormat.KEY_SAMPLE_RATE) ? Math.max(1, format.getInteger(MediaFormat.KEY_SAMPLE_RATE)) : 44_100;
    }

    private static class SegmentScore {

        private final double[] scores = new double[MAX_MIDI + 1];
        private int totalFrames;
        private int activeFrames;

        private void addFrame(FramePitch frame) {
            totalFrames++;
            if (frame == null || frame.values[0] < MIN_FRAME_ACTIVATION) return;
            activeFrames++;
            for (int i = 0; i < frame.pitches.length; i++) {
                int pitch = frame.pitches[i];
                double value = frame.values[i];
                if (pitch < MIN_MIDI || pitch > MAX_MIDI || value < MIN_FRAME_ACTIVATION * 0.55) continue;
                scores[pitch] += value;
                if (pitch > MIN_MIDI) scores[pitch - 1] += value * 0.12;
                if (pitch < MAX_MIDI) scores[pitch + 1] += value * 0.12;
            }
        }

        private List<KaraokePitchTrackGenerator.PitchCandidate> candidates() {
            if (totalFrames <= 0 || activeFrames < 2) return new ArrayList<>();
            double ratio = activeFrames / (double) totalFrames;
            double best = 0;
            for (int pitch = MIN_MIDI; pitch <= MAX_MIDI; pitch++) best = Math.max(best, scores[pitch]);
            double average = best / totalFrames;
            if (ratio < MIN_SEGMENT_RATIO || average < MIN_SEGMENT_SCORE) return new ArrayList<>();
            List<KaraokePitchTrackGenerator.PitchCandidate> result = new ArrayList<>();
            boolean[] used = new boolean[MAX_MIDI + 1];
            for (int count = 0; count < MAX_CANDIDATES; count++) {
                int bestPitch = -1;
                double bestScore = 0;
                for (int pitch = MIN_MIDI; pitch <= MAX_MIDI; pitch++) {
                    if (used[pitch]) continue;
                    if (scores[pitch] > bestScore) {
                        bestScore = scores[pitch];
                        bestPitch = pitch;
                    }
                }
                if (bestPitch < 0 || bestScore < best * 0.18) break;
                double quality = Math.max(0.05, Math.min(1, ratio * 0.70 + (bestScore / totalFrames) * 2.20));
                result.add(new KaraokePitchTrackGenerator.PitchCandidate(bestPitch, quality));
                for (int pitch = bestPitch - 1; pitch <= bestPitch + 1; pitch++) if (pitch >= MIN_MIDI && pitch <= MAX_MIDI) used[pitch] = true;
                for (int pitch = bestPitch - 24; pitch <= bestPitch + 24; pitch += 12) if (pitch >= MIN_MIDI && pitch <= MAX_MIDI) used[pitch] = true;
            }
            return result;
        }
    }

    private static class FramePitch {

        private final int[] pitches = new int[3];
        private final double[] values = new double[3];

        private void offer(int pitch, double value) {
            if (value <= values[values.length - 1]) return;
            for (int i = 0; i < values.length; i++) {
                if (value <= values[i]) continue;
                for (int j = values.length - 1; j > i; j--) {
                    values[j] = values[j - 1];
                    pitches[j] = pitches[j - 1];
                }
                values[i] = value;
                pitches[i] = pitch;
                return;
            }
        }
    }

    private static class AudioCollector {

        private final AudioBuffer output;
        private int sourceSampleRate;
        private double resampleStep;
        private long previousSourceIndex;
        private double nextOutputSourcePosition;
        private float previousSourceSample;
        private boolean hasPreviousSourceSample;

        private AudioCollector(int sourceSampleRate, AudioBuffer output) {
            this.output = output;
            setSourceSampleRate(sourceSampleRate);
        }

        private void setSourceSampleRate(int sourceSampleRate) {
            this.sourceSampleRate = Math.max(1, sourceSampleRate);
            this.resampleStep = this.sourceSampleRate / (double) SAMPLE_RATE;
        }

        private long sourceIndexOf(long presentationTimeUs) {
            return Math.max(0, Math.round(presentationTimeUs * sourceSampleRate / 1_000_000.0));
        }

        private void add(float sample, long sourceIndex) {
            sample = Math.max(-1f, Math.min(1f, sample));
            if (!hasPreviousSourceSample || sourceIndex <= previousSourceIndex || sourceIndex - previousSourceIndex > sourceSampleRate) {
                previousSourceSample = sample;
                previousSourceIndex = sourceIndex;
                nextOutputSourcePosition = sourceIndex;
                hasPreviousSourceSample = true;
                output.add(sample);
                nextOutputSourcePosition += resampleStep;
                return;
            }
            while (nextOutputSourcePosition <= sourceIndex) {
                double span = Math.max(1, sourceIndex - previousSourceIndex);
                double fraction = Math.max(0, Math.min(1, (nextOutputSourcePosition - previousSourceIndex) / span));
                output.add((float) (previousSourceSample + (sample - previousSourceSample) * fraction));
                nextOutputSourcePosition += resampleStep;
            }
            previousSourceSample = sample;
            previousSourceIndex = sourceIndex;
        }
    }

    private static class AudioBuffer {

        private float[] values;
        private int size;

        private AudioBuffer(int capacity) {
            values = new float[Math.max(SAMPLE_RATE, capacity)];
        }

        private void add(float value) {
            ensure(size + 1);
            values[size++] = value;
        }

        private float get(int index) {
            return index >= 0 && index < size ? values[index] : 0;
        }

        private int size() {
            return size;
        }

        private void ensure(int capacity) {
            if (capacity <= values.length) return;
            int next = Math.max(capacity, values.length + values.length / 2);
            float[] copy = new float[next];
            System.arraycopy(values, 0, copy, 0, size);
            values = copy;
        }
    }

    private static class OutputPlan {

        private final Map<Integer, Object> outputs = new HashMap<>();
        private final List<OutputTensor> tensors = new ArrayList<>();
        private OutputTensor note;
        private OutputTensor onset;

        private static OutputPlan from(Interpreter interpreter) {
            OutputPlan plan = new OutputPlan();
            for (int i = 0; i < interpreter.getOutputTensorCount(); i++) {
                Tensor tensor = interpreter.getOutputTensor(i);
                OutputTensor output = new OutputTensor(i, tensor.name(), tensor.shape());
                plan.tensors.add(output);
                plan.outputs.put(i, output.values);
                if (output.isNote()) plan.note = output;
                else if (output.isOnset()) plan.onset = output;
            }
            if (plan.note == null) {
                for (OutputTensor output : plan.tensors) {
                    if (output.lastDim() == 88) {
                        plan.note = output;
                        break;
                    }
                }
            }
            if (plan.onset == null) {
                for (OutputTensor output : plan.tensors) {
                    if (output != plan.note && output.lastDim() == 88) {
                        plan.onset = output;
                        break;
                    }
                }
            }
            return plan;
        }

        private void clear() {
            for (OutputTensor tensor : tensors) tensor.clear();
        }

        private String describe() {
            StringBuilder builder = new StringBuilder();
            for (OutputTensor tensor : tensors) {
                if (builder.length() > 0) builder.append(',');
                builder.append(tensor.name).append('[').append(tensor.shapeText()).append(']');
            }
            return builder.toString();
        }
    }

    private static class OutputTensor {

        private final int index;
        private final String name;
        private final int[] shape;
        private final float[][][] values;

        private OutputTensor(int index, String name, int[] shape) {
            this.index = index;
            this.name = name == null ? "" : name;
            this.shape = shape == null ? new int[0] : shape;
            int dim0 = Math.max(1, this.shape.length > 0 ? this.shape[0] : 1);
            int dim1 = Math.max(1, this.shape.length > 1 ? this.shape[1] : 1);
            int dim2 = Math.max(1, this.shape.length > 2 ? this.shape[2] : 1);
            this.values = new float[dim0][dim1][dim2];
        }

        private boolean isNote() {
            return lastDim() == 88 && name.toLowerCase(Locale.ROOT).contains("note");
        }

        private boolean isOnset() {
            return lastDim() == 88 && name.toLowerCase(Locale.ROOT).contains("onset");
        }

        private int lastDim() {
            return shape.length == 0 ? 0 : shape[shape.length - 1];
        }

        private void clear() {
            for (float[][] rows : values) for (float[] row : rows) for (int i = 0; i < row.length; i++) row[i] = 0;
        }

        private String shapeText() {
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < shape.length; i++) {
                if (i > 0) builder.append('x');
                builder.append(shape[i]);
            }
            return builder.toString();
        }
    }
}
