package com.fongmi.android.tv.player.karaoke;

import androidx.fragment.app.FragmentActivity;

import com.fongmi.android.tv.player.PlayerManager;
import com.fongmi.android.tv.player.lyrics.LyricsLine;
import com.fongmi.android.tv.setting.PlayerSetting;
import com.fongmi.android.tv.utils.PermissionUtil;
import com.fongmi.android.tv.utils.Task;

import java.util.List;

public class KaraokeController implements KaraokeMicRecorder.Listener {

    private final KaraokeTrackRepository repository = new KaraokeTrackRepository();
    private final KaraokeMicRecorder mic = new KaraokeMicRecorder();
    private KaraokePitchSample sample = new KaraokePitchSample(0, 0, 0, 0);
    private KaraokeScoreSnapshot snapshot = new KaraokeScoreSnapshot(0, 0, null, Double.NaN, Double.NaN, false, false);
    private KaraokeTrack track;
    private KaraokeScorer scorer;
    private KaraokeFreeSingScorer freeScorer;
    private String signature;
    private boolean active;
    private boolean micUnavailable;
    private boolean autoGenerating;
    private String autoGeneratedSignature;
    private int sequence;

    public interface Listener {
        void onKaraokeUpdate(KaraokeStatus status, KaraokeTrack track, KaraokePitchSample sample, KaraokeScoreSnapshot snapshot);
    }

    private Listener listener;

    public void setListener(Listener listener) {
        this.listener = listener;
    }

    public boolean isActive() {
        return active;
    }

    public KaraokeTrack getTrack() {
        return track;
    }

    public KaraokePitchSample getSample() {
        return sample;
    }

    public KaraokeScoreSnapshot getSnapshot() {
        return snapshot;
    }

    public KaraokeResult getResult() {
        return KaraokeResult.from(track, snapshot);
    }

    public void refresh(FragmentActivity activity, PlayerManager player, boolean available) {
        refresh(activity, player, available, true);
    }

    public void refresh(FragmentActivity activity, PlayerManager player, boolean available, boolean loadTrack) {
        boolean enabled = available && PlayerSetting.isKaraokeMode() && player != null && !player.isEmpty();
        if (!enabled) {
            clear();
            return;
        }
        active = true;
        micUnavailable = false;
        ensureMic(activity);
        String nextSignature = signatureOf(player);
        if (nextSignature.equals(signature)) return;
        signature = nextSignature;
        autoGenerating = false;
        autoGeneratedSignature = null;
        int current = ++sequence;
        long position = player.getPosition();
        track = null;
        scorer = null;
        freeScorer = new KaraokeFreeSingScorer(scoringConfig());
        snapshot = emptySnapshot(position);
        notifyUpdate();
        if (!loadTrack) return;
        repository.load(player, result -> {
            if (current != sequence || !active) return;
            track = result;
            if (result != null && result.hasScoredNotes()) {
                scorer = new KaraokeScorer(result, scoringConfig());
                freeScorer = null;
                snapshot = scorer.evaluate(adjustLyricsPosition(player), sample.getFrequencyHz(), sample.getVolume(), sample.getConfidence());
            } else {
                scorer = null;
                freeScorer = new KaraokeFreeSingScorer(scoringConfig());
                snapshot = emptySnapshot(adjustLyricsPosition(player));
            }
            notifyUpdate();
        });
    }

    public void reload(FragmentActivity activity, PlayerManager player, boolean available) {
        signature = null;
        autoGeneratedSignature = null;
        refresh(activity, player, available);
    }

    public void update(PlayerManager player) {
        update(player, null);
    }

    public void update(PlayerManager player, List<LyricsLine> lyrics) {
        if (!active || player == null || player.isEmpty()) return;
        long position = adjustLyricsPosition(player);
        if (!player.isPlaying()) {
            if (scorer != null) snapshot = scorer.evaluate(position, sample.getFrequencyHz(), sample.getVolume(), sample.getConfidence());
            notifyUpdate();
            return;
        }
        if (scorer != null) snapshot = scorer.update(position, sample.getFrequencyHz(), sample.getVolume(), sample.getConfidence());
        else if (freeScorer != null) {
            maybeAutoGenerate(player, lyrics);
            snapshot = freeScorer.update(position, sample, lyrics);
        }
        notifyUpdate();
    }

    public void clear() {
        sequence++;
        active = false;
        signature = null;
        track = null;
        scorer = null;
        freeScorer = null;
        micUnavailable = false;
        autoGenerating = false;
        autoGeneratedSignature = null;
        sample = new KaraokePitchSample(0, 0, 0, 0);
        snapshot = new KaraokeScoreSnapshot(0, 0, null, Double.NaN, Double.NaN, false, false);
        mic.stop();
        notifyUpdate();
    }

    public void release() {
        clear();
        listener = null;
    }

    @Override
    public void onPitch(KaraokePitchSample sample) {
        this.sample = sample == null ? new KaraokePitchSample(0, 0, 0, 0) : sample;
        micUnavailable = false;
        notifyUpdate();
    }

    @Override
    public void onError(Throwable error) {
        micUnavailable = true;
        notifyUpdate();
    }

    private void ensureMic(FragmentActivity activity) {
        if (mic.isRunning()) return;
        if (mic.hasPermission()) {
            micUnavailable = !mic.start(this);
            notifyUpdate();
            return;
        }
        if (activity == null) return;
        notifyUpdate();
        PermissionUtil.requestAudio(activity, granted -> {
            if (!active) return;
            if (granted) micUnavailable = !mic.start(this);
            notifyUpdate();
        });
    }

    private KaraokeScoringConfig scoringConfig() {
        return new KaraokeScoringConfig.Builder()
                .toleranceSemitones(PlayerSetting.getKaraokeToleranceSemitones())
                .inputLatencyMs(PlayerSetting.getKaraokeMicDelayMs())
                .build();
    }

    private void notifyUpdate() {
        if (listener != null) listener.onKaraokeUpdate(getStatus(), track, sample, snapshot);
    }

    private KaraokeStatus getStatus() {
        if (!active) return KaraokeStatus.INACTIVE;
        if (!mic.hasPermission()) return KaraokeStatus.NEED_PERMISSION;
        if (micUnavailable || !mic.isRunning()) return KaraokeStatus.MIC_UNAVAILABLE;
        return track != null && track.hasScoredNotes() ? KaraokeStatus.SCORING : KaraokeStatus.FREE_SING;
    }

    private void maybeAutoGenerate(PlayerManager player, List<LyricsLine> lyrics) {
        String currentSignature = signatureOf(player);
        if (autoGenerating || currentSignature.equals(autoGeneratedSignature)) return;
        if (!KaraokeTrackRepository.canGenerate(lyrics)) return;
        autoGenerating = true;
        autoGeneratedSignature = currentSignature;
        int current = sequence;
        Task.execute(() -> {
            KaraokeTrackRepository.ImportResult result = KaraokeTrackRepository.importAutoGenerated(player, lyrics);
            com.fongmi.android.tv.App.post(() -> onAutoGenerated(current, result));
        });
    }

    private void onAutoGenerated(int current, KaraokeTrackRepository.ImportResult result) {
        autoGenerating = false;
        if (current != sequence || !active || scorer != null || result == null || !result.isSuccess()) return;
        track = result.getTrack();
        scorer = new KaraokeScorer(track, scoringConfig());
        freeScorer = null;
        snapshot = emptySnapshot(0);
        notifyUpdate();
    }

    private static KaraokeScoreSnapshot emptySnapshot(long positionMs) {
        return new KaraokeScoreSnapshot(Math.max(0, positionMs), 0, 0, 0, 0, 0, null, Double.NaN, Double.NaN, false, false);
    }

    private static String signatureOf(PlayerManager player) {
        return KaraokeTrackRepository.identityOf(player);
    }

    private static long adjustLyricsPosition(PlayerManager player) {
        return Math.max(0, player.getPosition() + PlayerSetting.getLyricsTimeOffsetMs());
    }

}
